### ISSUE TITLE
With Traefik 2.0 you should be able to skip coreDNS all together...

### ISSUE THREAD

**Issue by PromoFaux** [kquinsland/skyhole#4]
Hi there,

Just came across this repo (after I finally got something similar working myself...)

But just a little hint, if you set up a file provider in Traefik, you should be able to use the following configuration:

```toml
[tcp]
  [tcp.routers]
    [tcp.routers.rou_dot]
      entryPoints = ["dot"]
      rule = "HostSNI(`[yourdomain.name.whatever]`)"
      service = "svc_dot"
      [tcp.routers.rou_dot.tls]
        certResolver = "le"

  [tcp.services]
    [tcp.services.svc_dot.loadBalancer]
    terminationDelay = 100
      [[tcp.services.svc_dot.loadBalancer.servers]]
        address = "[pi-hole-IP]:53"
```

Don't forget to include an entrypoint in the main `traefik.toml` file!

```toml
[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.web-secure]
    address = ":443"
  [entryPoints.dot]
    address = ":853"

```
